dubbo:
  application:
    name: merge-springboot-provider
    qos-enable: false
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://${zookeeper.address:127.0.0.1}:2181
  provider:
    token: "true"